define Package/dni-mtdoops/install_dniext
	$(INSTALL_BIN) $(LOCAL_DNI_FILES_EXT)/dni-debug.init $(1)/etc/init.d/
	$(INSTALL_BIN) $(LOCAL_DNI_FILES_EXT)/wireless_log.sh $(1)/sbin/
	$(INSTALL_BIN) $(LOCAL_DNI_FILES_EXT)/save_collect_console_log.sh $(1)/sbin/
endef

define Package/dni-mtdoops/prepare_dniext
endef

